/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    AppNavigation: typeof import('./components/layout/AppNavigation.vue')['default']
    AppToolbar: typeof import('./components/layout/AppToolbar.vue')['default']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    AuthConfirmOtpForm: typeof import('./components/pages/auth/AuthConfirmOtpForm.vue')['default']
    AuthLoginWithKey: typeof import('./components/pages/auth/AuthLoginWithKey.vue')['default']
    AuthLoginWithLoginAndPassword: typeof import('./components/pages/auth/AuthLoginWithLoginAndPassword.vue')['default']
    AuthToolBar: typeof import('./components/pages/auth/AuthToolBar.vue')['default']
    BalanceFilterList: typeof import('./components/pages/balance/BalanceFilterList.vue')['default']
    BalanceStatusForm: typeof import('./components/pages/balance/BalanceStatusForm.vue')['default']
    BankingFilterList: typeof import('./components/pages/BankingFilterList.vue')['default']
    EmptyText: typeof import('./components/base/EmptyText.vue')['default']
    ESignKey: typeof import('./components/base/ESign/ESignKey.vue')['default']
    ImageUploader: typeof import('./components/base/ImageUploader.vue')['default']
    MaskInput: typeof import('./components/base/MaskInput.vue')['default']
    PDFViewer: typeof import('./components/base/PDFViewer.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VImg: typeof import('./components/base/VImg.vue')['default']
    VStatus: typeof import('./components/base/VStatus.vue')['default']
    VText: typeof import('./components/base/VText.vue')['default']
    WithdrawFilterList: typeof import('./components/pages/WithdrawFilterList.vue')['default']
  }
}
