/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    AppNavigation: typeof import('./components/layout/AppNavigation.vue')['default']
    AppToolbar: typeof import('./components/layout/AppToolbar.vue')['default']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    AuthConfirmOtpForm: typeof import('./components/pages/auth/AuthConfirmOtpForm.vue')['default']
    AuthLoginWithKey: typeof import('./components/pages/auth/AuthLoginWithKey.vue')['default']
    AuthLoginWithLoginAndPassword: typeof import('./components/pages/auth/AuthLoginWithLoginAndPassword.vue')['default']
    AuthToolBar: typeof import('./components/pages/auth/AuthToolBar.vue')['default']
    EmptyText: typeof import('./components/base/EmptyText.vue')['default']
    ESignKey: typeof import('./components/base/ESign/ESignKey.vue')['default']
    HomeNodes: typeof import('./components/pages/home/HomeNodes.vue')['default']
    HomeNoteForm: typeof import('./components/pages/home/HomeNoteForm.vue')['default']
    HomeTaskList: typeof import('./components/pages/home/HomeTaskList.vue')['default']
    ImageUploader: typeof import('./components/base/ImageUploader.vue')['default']
    MaskInput: typeof import('./components/base/MaskInput.vue')['default']
    PDFViewer: typeof import('./components/base/PDFViewer.vue')['default']
    ProjectFormDialog: typeof import('./components/pages/projects/ProjectFormDialog.vue')['default']
    ProjectTableTopBar: typeof import('./components/pages/projects/ProjectTableTopBar.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VImg: typeof import('./components/base/VImg.vue')['default']
    VStatus: typeof import('./components/base/VStatus.vue')['default']
    VText: typeof import('./components/base/VText.vue')['default']
  }
}
